spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.NonRegisteringDriver
    url: jdbc:mysql://localhost:3306/spring_security?useSSL=false
    username: root
    password: buputi2789

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: MYSQL
    database-platform: org.hibernate.dialect.MySQL8Dialect
